# Generated by Django 5.1.5 on 2025-02-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
