# Generated by Django 5.1.5 on 2025-02-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
    ]
